# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['start_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('upload_person', 'Can upload monthly payroll'), ('export_person_rates', 'Can export person rates')), 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personcost',
            options={'ordering': ['start_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productgroupstatus',
            options={'ordering': ('-start_date', '-id'), 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ('-start_date', '-id'), 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-start_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['start_date', 'id']},
        ),
        migrations.AlterField(
            model_name='person',
            name='staff_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
