# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161026_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no repeat'), (1, 'weekly'), (2, 'monthly')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Person'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Person'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='delivery_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Person'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Person'),
        ),
        migrations.AlterField(
            model_name='productgroupstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'At risk'), (3, 'In trouble'), (4, 'Paused')], default=1),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'At risk'), (3, 'In trouble'), (4, 'Paused')], default=1),
        ),
    ]
