# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_personcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='staff_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
