# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-31 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170301_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('export_person_rates', 'Can export person rates'),), 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product'},
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(related_name='persons', to='dashboard.Skill'),
        ),
    ]
