# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0006_projectgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'At risk'), (3, 'In trouble')], default=1)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='prototype.ProjectGroup')),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'At risk'), (3, 'In trouble')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='prototype.Project')),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rag',
            name='project',
        ),
        migrations.DeleteModel(
            name='RAG',
        ),
    ]
