# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0009_rename_date_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupstatus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
