# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0010_project_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='alpha_date',
            field=models.DateField(blank=True, null=True, verbose_name='alpha start'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='beta_date',
            field=models.DateField(blank=True, null=True, verbose_name='beta start'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='discovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='discovery start'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='live_date',
            field=models.DateField(blank=True, null=True, verbose_name='live start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
