# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0013_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
