# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0014_budget_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('adjustmentexport_project', 'Can run Adjustment Export'), ('intercompanyexport_project', 'Can run Intercompany Export'), ('projectdetailexport_project', 'Can run Intercompany Export')), 'verbose_name': 'product'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Please enter the total budget', max_digits=16),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
