# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0015_remove_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField()),
                ('note', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='prototype.Project')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='personcost',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['start_date']},
        ),
    ]
