# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('float_id', models.CharField(max_length=64, unique=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('avatar', models.URLField(null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('float_id', models.CharField(max_length=64, unique=True)),
                ('discovery_date', models.DateField(null=True)),
                ('alpha_date', models.DateField(null=True)),
                ('beta_date', models.DateField(null=True)),
                ('live_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prototype.Client')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prototype.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='prototype.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_contractor', models.BooleanField()),
                ('people', models.ManyToManyField(through='prototype.PersonRole', to='prototype.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=5, max_digits=10)),
                ('float_id', models.CharField(max_length=64, unique=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prototype.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prototype.Project')),
            ],
        ),
        migrations.AddField(
            model_name='personrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.Role'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(through='prototype.PersonRole', to='prototype.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('name', 'is_contractor')]),
        ),
    ]
