# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('float_id', models.CharField(max_length=128, unique=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'One off'), (2, 'Monthly'), (3, 'Annually')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('avatar', models.URLField(null=True)),
                ('is_contractor', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=128, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('float_id', models.CharField(max_length=128, unique=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('alpha_date', models.DateField(blank=True, null=True)),
                ('beta_date', models.DateField(blank=True, null=True)),
                ('live_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prototype.Client')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prototype.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('rag', models.PositiveSmallIntegerField(choices=[(1, 'Green'), (2, 'Green/Amber'), (3, 'Amber'), (4, 'Amber/Red'), (5, 'Red')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rags', to='prototype.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.PositiveSmallIntegerField(choices=[(1, 'Dayly rate'), (2, 'Monthly salary'), (3, 'Yearly salary')], default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='prototype.Person')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=5, max_digits=10)),
                ('float_id', models.CharField(max_length=128, unique=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prototype.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prototype.Project')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='prototype.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('start_date', 'person')]),
        ),
    ]
