# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_auto_20160803_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
