# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_client_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alpha_date',
            field=models.DateField(blank=True, null=True, verbose_name='alpha start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='beta_date',
            field=models.DateField(blank=True, null=True, verbose_name='beta start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='discovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='discovery start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_date',
            field=models.DateField(blank=True, null=True, verbose_name='live start'),
        ),
    ]
