# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0011_abstract_base_project'),
        ('prototype', '0011_merge'),
    ]

    operations = [
    ]
