# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0012_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.Person', verbose_name='service manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.Person'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.Person'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='delivery_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.Person'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.Person'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='personcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prototype.Client', verbose_name='service area'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
    ]
