# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0012_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='personcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
    ]
